sources:
  - name: ETHRegistrarController
    handler:
      graphql:
        # endpoint: https://api.thegraph.com/subgraphs/name/doomling/ens-explorer
        endpoint: https://api.thegraph.com/subgraphs/id/QmS46BujTAgrcxuR58YiYUzZ2khoGEU5CYTxDeNee82Yyv
        # endpoint: https://api.studio.thegraph.com/query/41300/lalalala/0.0.4
    transforms:
      - blockTracking:
          validateSchema: true

      - autoPagination:
          validateSchema: true # Validates that the schema source actually contains the required input filters.
          limitOfRecords: 3000 # Default is 1000, you can change if you indexer has different configuration in GRAPH_GRAPHQL_MAX_FIRST var.
documents:
  - ./queries/ens-name-registered.graphql
  - ./queries/ens-history.graphql
  - ./queries/ens-transfers-per-day.graphql
plugins:
  - pollingLive:
      defaultInterval: 1000
